services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
  app:
    image: hello-front-dev
    build:
      context: ./todo-frontend
      dockerfile: dev.Dockerfile 
    volumes:
      - ./todo-frontend:/usr/src/app
    environment:
      - VITE_BACKEND_URL=http://api:3000
    container_name: hello-front-dev
  api:
    image: hello-back-dev
    build:
      context: ./todo-backend
      dockerfile: dev.Dockerfile 
    volumes:
      - ./todo-backend:/usr/src/app
    container_name: hello-back-dev
    environment:
      - NODE_ENV=development
      - REDIS_URL=http://redis:6379
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database
    depends_on:
      - mongo
      - redis
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - mongo-data:/data/db
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
  redis:
    image: redis
    volumes:
      - redis-data:/data
volumes:
  mongo-data:
  redis-data: